name: Build CI

on:
  push:
  pull_request:
  release:
    types: [published]
  workflow_dispatch:  # allow manual trigger

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Set up repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          filter: "blob:none"
          show-progress: false
          submodules: false

      - name: Set up compiler
        uses: carlosperate/arm-none-eabi-gcc-action@v1
        with:
          release: '13.2.Rel1'

      - name: Extract version identifier
        run: |
          echo >> $GITHUB_ENV "UF2_VERSION_BASE=`git describe --dirty --always --tags`"

      - name: Build PyGamer / Arcade
        run: |
          make submodules
          make -j$(nproc) arcade_pygamer
          # move the build output to a predictable path
          mkdir -p build/uf2
          mv build/arcade_pygamer/*.uf2 build/uf2/uf2-arcade-pygamer-${{ env.UF2_VERSION_BASE }}.uf2

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: build/uf2/uf2-arcade-pygamer-${{ env.UF2_VERSION_BASE }}.uf2
          name: uf2-arcade-pygamer-${{ env.UF2_VERSION_BASE }}
